### ISSUE TITLE
USBEndpointDescriptor alignment

### ISSUE THREAD

**Issue by javier-box** [atmelcorp/atmel-software-package#17]
dabort, invalid opcode(ldrh r3, [r3, #4]) when MMU strict alignment is enabled on the function below. This stop when endpoint.bInterval is changed from uint8_t to uint16_t. If strict alignment is disabled then the demo ramdisk and emmc appear write protected when they are not, indicating an unalign data struct.

/**
-  Returns the maximum size of a packet (in bytes) on an endpoint given
-  its descriptor.
-  \param endpoint - Pointer to a USBEndpointDescriptor instance.
-  \return Maximum packet size of endpoint.
  */
  uint16_t usb_endpoint_descriptor_get_max_packet_size(
  const USBEndpointDescriptor *endpoint)
  {
  return endpoint->wMaxPacketSize;
  }

**Comment by loiclefort** [comment]
@javier-box the USB endpoint descriptor structure is defined in the USB specification so we cannot change any field size or add padding. The current USB stack relies on the fact that the Cortex-A5 can do unaligned accesses.
You can try adding -mno-unaligned-access to CFLAGS to see if the issue you are observing if really due to an unaligned access problem.
